// Code generated by cmd/generate from the Futrou OpenAPI spec. DO NOT EDIT.
// Generated at: 2026-07-22T17:41:22Z
// Source: https://api.futrou.com/v2/openapi.json

package api

import "time"

// APIError represents a structured error response from the Futrou API.
type APIError struct {
	Message   string       `json:"message"`
	RequestId string       `json:"requestId"`
	ClientIp  string       `json:"clientIp"`
	Errors    []FieldError `json:"errors"`
}

func (e *APIError) Error() string {
	return e.Message
}

// FieldError is a single validation error within an APIError.
type FieldError struct {
	Message string `json:"message"`
	Code    string `json:"code"`
	Field   string `json:"field"`
}

// LoginResponse is returned from POST /v2/auth/login.
type LoginResponse struct {
	ApiToken ApiToken `json:"apiToken"`
	User     User     `json:"user"`
}

// Activity Activity (Model)
type Activity struct {
	CreatedAt time.Time `json:"createdAt,omitempty"`
	ExpiresAt time.Time `json:"expiresAt,omitempty"`
	Id string `json:"id,omitempty"`
	NewValues map[string]interface{} `json:"newValues,omitempty"`
	OldValues map[string]interface{} `json:"oldValues,omitempty"`
	ProjectId string `json:"projectId,omitempty"`
	ProjectIdLabel string `json:"projectIdLabel,omitempty"`
	RegionId string `json:"regionId,omitempty"`
	RegionIdLabel string `json:"regionIdLabel,omitempty"`
	ServerId string `json:"serverId,omitempty"`
	ServerIdLabel string `json:"serverIdLabel,omitempty"`
	ServerletId string `json:"serverletId,omitempty"`
	ServerletIdLabel string `json:"serverletIdLabel,omitempty"`
	Type *ActivityType `json:"type,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	User *User `json:"user,omitempty"`
	UserId string `json:"userId,omitempty"`
	UserIdLabel string `json:"userIdLabel,omitempty"`
	VolumeId string `json:"volumeId,omitempty"`
	VolumeIdLabel string `json:"volumeIdLabel,omitempty"`
	Workspace *Workspace `json:"workspace,omitempty"`
	WorkspaceId string `json:"workspaceId,omitempty"`
	WorkspaceIdLabel string `json:"workspaceIdLabel,omitempty"`
	WorkspaceUser *WorkspaceUser `json:"workspaceUser,omitempty"`
	WorkspaceUserId string `json:"workspaceUserId,omitempty"`
	WorkspaceUserIdLabel string `json:"workspaceUserIdLabel,omitempty"`
}

// ActivityType Activity Type enumeration
type ActivityType struct {
}

// Any Any JSON object not defined as schema
type Any struct {
}

// ApiToken ApiToken (Interface)
type ApiToken struct {
	CreatedAt string `json:"createdAt,omitempty"`
	ExpiresAt string `json:"expiresAt,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Token string `json:"token,omitempty"`
	Type string `json:"type,omitempty"`
	UpdatedAt string `json:"updatedAt,omitempty"`
}

// App App (Model)
type App struct {
	AllowedPermissions []map[string]interface{} `json:"allowedPermissions,omitempty"`
	ApiTokens []ApiToken `json:"apiTokens,omitempty"`
	AuthorizationCodes []OauthAuthorizationCode `json:"authorizationCodes,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	RedirectUris []string `json:"redirectUris,omitempty"`
	Type *OAuth2Type `json:"type,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	Workspace *Workspace `json:"workspace,omitempty"`
	WorkspaceId string `json:"workspaceId,omitempty"`
}

// Arch Arch enumeration
type Arch struct {
}

// Contact Contact (Model)
type Contact struct {
	City string `json:"city,omitempty"`
	Company string `json:"company,omitempty"`
	CompanyNumber string `json:"companyNumber,omitempty"`
	Country map[string]interface{} `json:"country,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	Email string `json:"email,omitempty"`
	Firstname string `json:"firstname,omitempty"`
	Id string `json:"id,omitempty"`
	IsPersonal bool `json:"isPersonal,omitempty"`
	Lastname string `json:"lastname,omitempty"`
	Phone string `json:"phone,omitempty"`
	PostalCode string `json:"postalCode,omitempty"`
	StreetAddress string `json:"streetAddress,omitempty"`
	StreetAddress2 string `json:"streetAddress2,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	VatNumber string `json:"vatNumber,omitempty"`
	Workspace *Workspace `json:"workspace,omitempty"`
}

// Cron Cron (Model)
type Cron struct {
	Body string `json:"body,omitempty"`
	Code string `json:"code,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	CronPlan *CronPlan `json:"cronPlan,omitempty"`
	CronPlanId string `json:"cronPlanId,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	Headers map[string]string `json:"headers,omitempty"`
	Id string `json:"id,omitempty"`
	Method string `json:"method,omitempty"`
	Name string `json:"name,omitempty"`
	Project *Project `json:"project,omitempty"`
	ProjectId string `json:"projectId,omitempty"`
	Region *Region `json:"region,omitempty"`
	RegionId string `json:"regionId,omitempty"`
	Schedule string `json:"schedule,omitempty"`
	StartedAt time.Time `json:"startedAt,omitempty"`
	Type *CronType `json:"type,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	Url string `json:"url,omitempty"`
	Workspace *Workspace `json:"workspace,omitempty"`
	WorkspaceId string `json:"workspaceId,omitempty"`
}

// CronPlan CronPlan (Model)
type CronPlan struct {
	CreatedAt time.Time `json:"createdAt,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	Id string `json:"id,omitempty"`
	IsPublic bool `json:"isPublic,omitempty"`
	MinutePrice map[string]float64 `json:"minutePrice,omitempty"`
	MonthlyPrice map[string]float64 `json:"monthlyPrice,omitempty"`
	Name string `json:"name,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}

// CronType Cron Type enumeration
type CronType struct {
}

// Currency Currency enumeration
type Currency struct {
}

// Deployment Deployment (Model)
type Deployment struct {
	Active bool `json:"active,omitempty"`
	Config map[string]interface{} `json:"config,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	Id string `json:"id,omitempty"`
	Number float64 `json:"number,omitempty"`
	Project *Project `json:"project,omitempty"`
	ProjectId string `json:"projectId,omitempty"`
	Status *DeploymentStatus `json:"status,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	Workspace *Workspace `json:"workspace,omitempty"`
	WorkspaceId string `json:"workspaceId,omitempty"`
}

// DeploymentStatus Deployment Status enumeration
type DeploymentStatus struct {
}

// Invoice Invoice (Model)
type Invoice struct {
	CanceledAt time.Time `json:"canceledAt,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	Currency *Currency `json:"currency,omitempty"`
	CustomerContact *Contact `json:"customerContact,omitempty"`
	CustomerContactId string `json:"customerContactId,omitempty"`
	DueAt time.Time `json:"dueAt,omitempty"`
	ExchangeRate float64 `json:"exchangeRate,omitempty"`
	ExchangeRateCurrency *Currency `json:"exchangeRateCurrency,omitempty"`
	Id string `json:"id,omitempty"`
	IssuedAt time.Time `json:"issuedAt,omitempty"`
	Items []InvoiceItem `json:"items,omitempty"`
	Language *Language `json:"language,omitempty"`
	Number string `json:"number,omitempty"`
	Order *Order `json:"order,omitempty"`
	OrderId string `json:"orderId,omitempty"`
	PaidAt time.Time `json:"paidAt,omitempty"`
	PdfKey string `json:"pdfKey,omitempty"`
	Price float64 `json:"price,omitempty"`
	ReferenceNumber string `json:"referenceNumber,omitempty"`
	RefundedAt time.Time `json:"refundedAt,omitempty"`
	Status *InvoiceStatus `json:"status,omitempty"`
	SupplierContact *Contact `json:"supplierContact,omitempty"`
	SupplierContactId string `json:"supplierContactId,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	Workspace *Workspace `json:"workspace,omitempty"`
	WorkspaceId string `json:"workspaceId,omitempty"`
}

// InvoiceItem InvoiceItem (Interface)
type InvoiceItem struct {
	Description string `json:"description,omitempty"`
	Quantity float64 `json:"quantity,omitempty"`
	Unit string `json:"unit,omitempty"`
	UnitPrice float64 `json:"unitPrice,omitempty"`
}

// InvoiceStatus Invoice Status enumeration
type InvoiceStatus struct {
}

// Language Language enumeration
type Language struct {
}

// OAuth2Type Oauth2type enumeration
type OAuth2Type struct {
}

// OauthAuthorizationCode OauthAuthorizationCode (Model)
type OauthAuthorizationCode struct {
	App *App `json:"app,omitempty"`
	AppId string `json:"appId,omitempty"`
	Code string `json:"code,omitempty"`
	CodeChallenge string `json:"codeChallenge,omitempty"`
	CodeChallengeMethod map[string]interface{} `json:"codeChallengeMethod,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	ExpiresAt time.Time `json:"expiresAt,omitempty"`
	Id string `json:"id,omitempty"`
	Permissions []map[string]interface{} `json:"permissions,omitempty"`
	RedirectUri string `json:"redirectUri,omitempty"`
	UsedAt time.Time `json:"usedAt,omitempty"`
	User *User `json:"user,omitempty"`
	UserId string `json:"userId,omitempty"`
	WorkspaceId string `json:"workspaceId,omitempty"`
}

// Order Order (Model)
type Order struct {
	CanceledAt time.Time `json:"canceledAt,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	CreemCheckoutId string `json:"creemCheckoutId,omitempty"`
	CreemProductId string `json:"creemProductId,omitempty"`
	CreemTransactionId string `json:"creemTransactionId,omitempty"`
	Currency *Currency `json:"currency,omitempty"`
	Id string `json:"id,omitempty"`
	Invoices []Invoice `json:"invoices,omitempty"`
	Number string `json:"number,omitempty"`
	PaidAt time.Time `json:"paidAt,omitempty"`
	PaymentMethod *PaymentMethod `json:"paymentMethod,omitempty"`
	Price float64 `json:"price,omitempty"`
	ProformaInvoices []ProformaInvoice `json:"proformaInvoices,omitempty"`
	RefundedAt time.Time `json:"refundedAt,omitempty"`
	Status *OrderStatus `json:"status,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	Workspace *Workspace `json:"workspace,omitempty"`
	WorkspaceId string `json:"workspaceId,omitempty"`
}

// OrderStatus Order Status enumeration
type OrderStatus struct {
}

// PaymentMethod Payment Method enumeration
type PaymentMethod struct {
}

// ProformaInvoice ProformaInvoice (Model)
type ProformaInvoice struct {
	CreatedAt time.Time `json:"createdAt,omitempty"`
	Currency *Currency `json:"currency,omitempty"`
	CustomerContact *Contact `json:"customerContact,omitempty"`
	CustomerContactId string `json:"customerContactId,omitempty"`
	DueAt time.Time `json:"dueAt,omitempty"`
	ExchangeRate float64 `json:"exchangeRate,omitempty"`
	ExchangeRateCurrency *Currency `json:"exchangeRateCurrency,omitempty"`
	Id string `json:"id,omitempty"`
	IssuedAt time.Time `json:"issuedAt,omitempty"`
	Items []ProformaInvoiceItem `json:"items,omitempty"`
	Language *Language `json:"language,omitempty"`
	Number string `json:"number,omitempty"`
	Order *Order `json:"order,omitempty"`
	OrderId string `json:"orderId,omitempty"`
	PdfKey string `json:"pdfKey,omitempty"`
	Price float64 `json:"price,omitempty"`
	ReferenceNumber string `json:"referenceNumber,omitempty"`
	SupplierContact *Contact `json:"supplierContact,omitempty"`
	SupplierContactId string `json:"supplierContactId,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	Workspace *Workspace `json:"workspace,omitempty"`
	WorkspaceId string `json:"workspaceId,omitempty"`
}

// ProformaInvoiceItem ProformaInvoiceItem (Interface)
type ProformaInvoiceItem struct {
	Description string `json:"description,omitempty"`
	Quantity float64 `json:"quantity,omitempty"`
	Unit string `json:"unit,omitempty"`
	UnitPrice float64 `json:"unitPrice,omitempty"`
}

// Project Project (Model)
type Project struct {
	CreatedAt time.Time `json:"createdAt,omitempty"`
	Crons []Cron `json:"crons,omitempty"`
	Deployments []Deployment `json:"deployments,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	GitRepositoryName string `json:"gitRepositoryName,omitempty"`
	GitRepositoryUrl string `json:"gitRepositoryUrl,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	Workspace *Workspace `json:"workspace,omitempty"`
	WorkspaceId string `json:"workspaceId,omitempty"`
}

// Proxy Proxy (Interface)
type Proxy struct {
	Compress bool `json:"compress,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
	Domain string `json:"domain,omitempty"`
	EnforceHttps bool `json:"enforceHttps,omitempty"`
	FollowRedirects bool `json:"followRedirects,omitempty"`
	Id string `json:"id,omitempty"`
	Port float64 `json:"port,omitempty"`
	PreserveHeaders bool `json:"preserveHeaders,omitempty"`
	PreserveHost bool `json:"preserveHost,omitempty"`
	PreservePath bool `json:"preservePath,omitempty"`
	PreserveQuery bool `json:"preserveQuery,omitempty"`
	Status string `json:"status,omitempty"`
	Strategy string `json:"strategy,omitempty"`
	Target string `json:"target,omitempty"`
	Type string `json:"type,omitempty"`
	UpdatedAt string `json:"updatedAt,omitempty"`
	VerifyTls bool `json:"verifyTls,omitempty"`
}

// Region Region (Model)
type Region struct {
	CreatedAt time.Time `json:"createdAt,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	Domain string `json:"domain,omitempty"`
	Id string `json:"id,omitempty"`
	IsPublic bool `json:"isPublic,omitempty"`
	Name string `json:"name,omitempty"`
	Servers []Server `json:"servers,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	Workspace *Workspace `json:"workspace,omitempty"`
	WorkspaceId string `json:"workspaceId,omitempty"`
}

// Server Server (Model)
type Server struct {
	ApiCertHash string `json:"apiCertHash,omitempty"`
	ApiHost string `json:"apiHost,omitempty"`
	ApiPort string `json:"apiPort,omitempty"`
	ApiTokens []ApiToken `json:"apiTokens,omitempty"`
	Arch *Arch `json:"arch,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	Domain string `json:"domain,omitempty"`
	Id string `json:"id,omitempty"`
	IsPublic bool `json:"isPublic,omitempty"`
	JoinedAt time.Time `json:"joinedAt,omitempty"`
	Name string `json:"name,omitempty"`
	Region *Region `json:"region,omitempty"`
	RegionId string `json:"regionId,omitempty"`
	SeenAt time.Time `json:"seenAt,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	WorkspaceId string `json:"workspaceId,omitempty"`
}

// Serverlet Serverlet (Interface)
type Serverlet struct {
	Cpu float64 `json:"cpu,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
	Id string `json:"id,omitempty"`
	Image string `json:"image,omitempty"`
	Instances float64 `json:"instances,omitempty"`
	MaxInstances float64 `json:"maxInstances,omitempty"`
	MinInstances float64 `json:"minInstances,omitempty"`
	Name string `json:"name,omitempty"`
	NetworkId string `json:"networkId,omitempty"`
	Ram float64 `json:"ram,omitempty"`
	Runtime string `json:"runtime,omitempty"`
	State string `json:"state,omitempty"`
	UpdatedAt string `json:"updatedAt,omitempty"`
}

// ServerletInstance ServerletInstance (Interface)
type ServerletInstance struct {
	Cpu float64 `json:"cpu,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
	Id string `json:"id,omitempty"`
	Image string `json:"image,omitempty"`
	Metrics map[string]interface{} `json:"metrics,omitempty"`
	Number float64 `json:"number,omitempty"`
	Ram float64 `json:"ram,omitempty"`
	Runtime string `json:"runtime,omitempty"`
	ServerId string `json:"serverId,omitempty"`
	ServerletId string `json:"serverletId,omitempty"`
	State string `json:"state,omitempty"`
	UpdatedAt string `json:"updatedAt,omitempty"`
	Version float64 `json:"version,omitempty"`
}

// ServerletPlan ServerletPlan (Model)
type ServerletPlan struct {
	Capacity map[string]interface{} `json:"capacity,omitempty"`
	Cpu float64 `json:"cpu,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	Id string `json:"id,omitempty"`
	IsPublic bool `json:"isPublic,omitempty"`
	MinutePrice map[string]float64 `json:"minutePrice,omitempty"`
	MonthlyPrice map[string]float64 `json:"monthlyPrice,omitempty"`
	Name string `json:"name,omitempty"`
	Ram map[string]interface{} `json:"ram,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}

// StaffRole Staff Role enumeration
type StaffRole struct {
}

// Transaction Transaction (Model)
type Transaction struct {
	CreatedAt time.Time `json:"createdAt,omitempty"`
	Currency *Currency `json:"currency,omitempty"`
	Description string `json:"description,omitempty"`
	Id string `json:"id,omitempty"`
	Price float64 `json:"price,omitempty"`
	Project *Project `json:"project,omitempty"`
	ProjectId string `json:"projectId,omitempty"`
	Type string `json:"type,omitempty"`
	Unit string `json:"unit,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	Value float64 `json:"value,omitempty"`
	Workspace *Workspace `json:"workspace,omitempty"`
	WorkspaceId string `json:"workspaceId,omitempty"`
}

// TwoFaType Two Fa Type enumeration
type TwoFaType struct {
}

// User User (Model)
type User struct {
	ActiveStaffRole *StaffRole `json:"activeStaffRole,omitempty"`
	Activities []Activity `json:"activities,omitempty"`
	ApiTokens []ApiToken `json:"apiTokens,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	Email string `json:"email,omitempty"`
	Fullname string `json:"fullname,omitempty"`
	Id string `json:"id,omitempty"`
	IsEmailConfirmed bool `json:"isEmailConfirmed,omitempty"`
	IsStaff bool `json:"isStaff,omitempty"`
	OauthAccessTokens []OauthAuthorizationCode `json:"oauthAccessTokens,omitempty"`
	RegistrationIp string `json:"registrationIp,omitempty"`
	SsoAvatarUrl string `json:"ssoAvatarUrl,omitempty"`
	SsoGithubId string `json:"ssoGithubId,omitempty"`
	SsoGitlabId string `json:"ssoGitlabId,omitempty"`
	SsoGoogleId string `json:"ssoGoogleId,omitempty"`
	SsoMicrosoftId string `json:"ssoMicrosoftId,omitempty"`
	SsoZohoId string `json:"ssoZohoId,omitempty"`
	StaffRole *StaffRole `json:"staffRole,omitempty"`
	TwoFaBackupCodes []string `json:"twoFaBackupCodes,omitempty"`
	TwoFaType *TwoFaType `json:"twoFaType,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	WorkspaceUsers []WorkspaceUser `json:"workspaceUsers,omitempty"`
	Workspaces *Any `json:"workspaces,omitempty"`
}

// Variable Variable (Model)
type Variable struct {
	CreatedAt time.Time `json:"createdAt,omitempty"`
	Description string `json:"description,omitempty"`
	Id string `json:"id,omitempty"`
	IsSecret bool `json:"isSecret,omitempty"`
	Key string `json:"key,omitempty"`
	Project *Project `json:"project,omitempty"`
	ProjectId string `json:"projectId,omitempty"`
	Serverlet *Serverlet `json:"serverlet,omitempty"`
	ServerletId string `json:"serverletId,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	Workspace *Workspace `json:"workspace,omitempty"`
	WorkspaceId string `json:"workspaceId,omitempty"`
}

// Volume Volume (Interface)
type Volume struct {
	CreatedAt string `json:"createdAt,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	SizeGb float64 `json:"sizeGb,omitempty"`
	Type string `json:"type,omitempty"`
	UpdatedAt string `json:"updatedAt,omitempty"`
}

// Voucher Voucher (Model)
type Voucher struct {
	Code string `json:"code,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	Currency *Currency `json:"currency,omitempty"`
	ExpiresAt time.Time `json:"expiresAt,omitempty"`
	Id string `json:"id,omitempty"`
	IsExpired bool `json:"isExpired,omitempty"`
	IsUsed bool `json:"isUsed,omitempty"`
	Price float64 `json:"price,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	UsedAt time.Time `json:"usedAt,omitempty"`
	UsedByWorkspace *Workspace `json:"usedByWorkspace,omitempty"`
	UsedByWorkspaceId string `json:"usedByWorkspaceId,omitempty"`
	Workspace *Workspace `json:"workspace,omitempty"`
	WorkspaceId string `json:"workspaceId,omitempty"`
}

// Workspace Workspace (Model)
type Workspace struct {
	Activities []Activity `json:"activities,omitempty"`
	ApiTokensLimit float64 `json:"apiTokensLimit,omitempty"`
	AutoJoinDomain string `json:"autoJoinDomain,omitempty"`
	AutoJoinRole *WorkspaceRole `json:"autoJoinRole,omitempty"`
	Contact *Contact `json:"contact,omitempty"`
	ContactId string `json:"contactId,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	Credit float64 `json:"credit,omitempty"`
	Crons []Cron `json:"crons,omitempty"`
	CronsLimit float64 `json:"cronsLimit,omitempty"`
	Currency *Currency `json:"currency,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	DnsLimit float64 `json:"dnsLimit,omitempty"`
	FeatureFlags []string `json:"featureFlags,omitempty"`
	Id string `json:"id,omitempty"`
	Language *Language `json:"language,omitempty"`
	Name string `json:"name,omitempty"`
	Number float64 `json:"number,omitempty"`
	Orders []Order `json:"orders,omitempty"`
	Projects []Project `json:"projects,omitempty"`
	ProjectsLimit float64 `json:"projectsLimit,omitempty"`
	ProxiesLimit float64 `json:"proxiesLimit,omitempty"`
	ServerletsLimit float64 `json:"serverletsLimit,omitempty"`
	ServersLimit float64 `json:"serversLimit,omitempty"`
	Transactions []Transaction `json:"transactions,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	Users *Any `json:"users,omitempty"`
	VolumesLimit float64 `json:"volumesLimit,omitempty"`
	Vouchers []Voucher `json:"vouchers,omitempty"`
	WorkspaceUsers []WorkspaceUser `json:"workspaceUsers,omitempty"`
	WorkspaceUsersLimit float64 `json:"workspaceUsersLimit,omitempty"`
}

// WorkspaceRole Workspace roles that users can have (hierarchy from lowest to highest)
type WorkspaceRole struct {
}

// WorkspaceUser WorkspaceUser (Model)
type WorkspaceUser struct {
	CreatedAt time.Time `json:"createdAt,omitempty"`
	Id string `json:"id,omitempty"`
	ProjectIds []string `json:"projectIds,omitempty"`
	Role *WorkspaceRole `json:"role,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	User *User `json:"user,omitempty"`
	UserId string `json:"userId,omitempty"`
	Workspace *Workspace `json:"workspace,omitempty"`
	WorkspaceId string `json:"workspaceId,omitempty"`
}

