name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'NPM version tag (e.g., latest, next)'
        required: true
        type: string
        default: 'next'

jobs:
  run:
    uses: ./.github/workflows/release-run.yml
    with:
      version_tag: ${{ github.event_name == 'release' && 'latest' || inputs.version_tag }}
    secrets: inherit
