name: Test

on:
  push:
    branches: ['**']
    tags-ignore: ['v*']
  pull_request:

env:
  DEBIAN_FRONTEND: noninteractive
  GO_VERSION: '1.25.x'
  NODE_VERSION: '24.x'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-slim
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Install dependencies
        run: make install

      - name: Build
        run: make build

      - name: Test
        run: make test
